services:
  mediawiki:
    image: mediawiki
    restart: always
    networks:
      - mediawiki_network
    ports:
      - 8082:80
    volumes:
      - mediawiki_files:/var/www/html/
  mediawiki-db:
    image: mysql:5.7
    restart: always
    networks:
      - mediawiki_network
    environment:
      MYSQL_DATABASE: wiki_db
      MYSQL_ROOT_PASSWORD: Nohay2sin3
      MYSQL_USER: wikimedia
      MYSQL_PASSWORD: wikimedia
    volumes:
      - mediawiki_data:/var/lib/mysql
  phpmyadmin-mediawiki:
    depends_on:
      - mediawiki-db
    image: phpmyadmin/phpmyadmin:5.2.1
    networks:
      - mediawiki_network
    container_name: phpmyadmin-mediawiki
    restart: always
    ports:
      - 8280:80
    environment:
      PMA_HOST: mediawiki-db
      MYSQL_ROOT_PASSWORD: wikimedia
networks:
  mediawiki_network:
    driver: bridge
volumes:
  mediawiki_data:
  mediawiki_files:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '~/mediawiki-content'

