name: ${USER}-wordpress
services:
  wordpress:
    image: wordpress:6.7.1
    container_name: wordpress
    volumes:
      - ${HOME}/wp-content:/var/www/html/wp-content
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=wordpress-db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=Nohay2sin3
    depends_on:
      - wordpress-db
      - phpmyadmin
    restart: always
    ports:
      - 8081:80

  wordpress-db:
    image: mysql:5.7
    container_name: wordpress-db
    volumes:
      - wordpress_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Nohay2sin3
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=Nohay2sin3
      - MYSQL_DATABASE=wordpress
    restart: always
  phpmyadmin:
    depends_on:
      - wordpress-db
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: always
    ports:
      - 8180:80
    environment:
      PMA_HOST: wordpress-db
      MYSQL_ROOT_PASSWORD: Nohay2sin3

volumes:
  wordpress_data:
